### ISSUE TITLE
Add flag to obtain a Git remote link to a given zettel

### ISSUE THREAD

**Issue by tpwo** [tpwo/pyzet#20]
E.g. it can use `git remote -v` to obtain a base URL, and then generate a link to a given zettel.

It can be either a part of `pyzet show` or I can add a new command for it. Theoretically, Python can tell the browser to open a new card, but it can be hard with some configurations like WSL.

**Comment by wojdatto** [comment]
This command should be something like:

```
pyzet show --remote
```

And the output should be the full link to the zettel ID (e.g. `20220416171827`) folder:

```
https://github.com/username/zet/tree/main/zettels/20220416171827
```

However, the construction of this link is different for different Git hostings. E.g. for Gitlab:

```
https://gitlab.com/username/zet/-/tree/main/zettels/20220416171827
```

or Bitbucket:

```
https://bitbucket.org/username/zet/src/main/zettels/20220416171827
```

One solution is to add a new field to the config file where the user can configure the base link for his hosting.

Alternatively, pyzet can parse the remote link and support some most popular choices (e.g. the three mentioned above).

Or, even better solution is to support the most popular platforms (with possible extending of them in the future) along with a new optional field in the config file that should be used for more niche hostings.

This will require some more work, but is probably worth it.
